### ISSUE TITLE
install.sh does not work - part 2

### ISSUE THREAD

**Issue by abeckers** [bluskript/raspicam-rs#2]
after changing the checkout directory to `raspicam-build`, cmake complains:
```
Could not find mmal libraries
```
Could you add to the docs how to install?

**Comment by abeckers** [comment]
I followed the advice in https://stackoverflow.com/questions/27777547/missing-libmmal-so-with-picamera-library to update the firmware
```
sudo rpi-update
```
and end with the following errors:
```
[ 36%] Linking CXX shared library libraspicam_cv.so
/usr/bin/ld: /opt/vc/lib/libmmal_core.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/raspicam_cv.dir/build.make:248: src/libraspicam_cv.so] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:170: src/CMakeFiles/raspicam_cv.dir/all] Fehler 2
make: *** [Makefile:149: all] Fehler 2
[  4%] Linking CXX shared library libraspicam_cv.so
/usr/bin/ld: /opt/vc/lib/libmmal_core.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/raspicam_cv.dir/build.make:248: src/libraspicam_cv.so] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:170: src/CMakeFiles/raspicam_cv.dir/all] Fehler 2
make: *** [Makefile:149: all] Fehler 2
```

**Comment by bluskript** [comment]
Are you using 64 bit Raspbian? MMAL is notoriously.. messed up on x64.
Historically raspberry pis would always be running in 32 bit

**Comment by bluskript** [comment]
Ironically the raspberry pi team appears to have moved on to use libcamera since I last used their camera stack.

In its current state, though, libcamera feels much like a Wayland sort of deal. MMAL is proprietary but it is better at offloading to the camera's onboard GPU. If you truly want the best performance, I'd recommend using the legacy camera stack. However, this unfortunately means that 64 bit is out of the question for this package because MMAL doesn't support it. I have added a notice about it.

https://github.com/raspberrypi/userland/issues/688

**Comment by abeckers** [comment]
Yes, I'm on 64 bit. Performance isn't an issue in my project. I think I will write my own wrapper around libcamera.
